// This file is generated by Slice Machine. Update with care!

import Cover from './Cover';
import Features from './Features';
import ImageAndText from './ImageAndText';
import Logos from './Logos';
import Numbers from './Numbers';
import Teasers from './Teasers';
import Testimonials from './Testimonials';

export {
	Cover,
	Features,
	ImageAndText,
	Logos,
	Numbers,
	Teasers,
	Testimonials,
};

export const components = {
	cover: Cover,
	features: Features,
	image_and_text: ImageAndText,
	logos: Logos,
	numbers: Numbers,
	teasers: Teasers,
	testimonials: Testimonials,
};
